import XCTest
import StoreKit
@testable import NutritionCoach

/// What can be tested without a working StoreKit configuration.
///
/// The purchase path itself is not unit-tested. `SKTestSession` refused every
/// hand-written `Configuration.storekit` — it parses the file without
/// complaint and then reports zero products, with no error to say why — and
/// the format is not documented well enough to guess at. A configuration
/// generated by Xcode (ideally synced from App Store Connect) is the fix, and
/// then `StoreKitTest` can drive purchase and restore properly.
///
/// Until then the purchase flow is verified by running it: the Simulator with
/// a valid configuration, and a Sandbox account on a device.
@MainActor
final class StoreTests: XCTestCase {
    func testTheProductIdentifiersAreExactlyWhatAppStoreConnectHas() {
        // Product IDs cannot be changed or reused once created. A typo here is
        // permanent, and shows up as a paywall with nothing on it — the same
        // symptom as an inactive Paid Applications agreement, which is why it
        // is worth pinning rather than eyeballing.
        XCTAssertEqual(
            Store.productIDs,
            [
                "dev.myhumblecoder.nutritioncoach.monthly",
                "dev.myhumblecoder.nutritioncoach.annual",
            ]
        )
    }

    func testMonthlyIsListedFirst() {
        // The paywall shows them in this order: monthly is the one most people
        // take, and the annual only reads as a saving standing next to it.
        XCTAssertEqual(Store.productIDs.first, "dev.myhumblecoder.nutritioncoach.monthly")
    }

    func testAStoreWithNoProductsIsNotEntitledToAnything() async {
        // The state a paywall must survive: products failed to load, so there
        // is nothing to buy. It has to say so rather than render an empty
        // sheet with a dead button.
        let store = Store(submit: { _ in true })

        XCTAssertTrue(store.products.isEmpty)
        XCTAssertFalse(store.isPurchasing)
    }

    func testOrderingSurvivesAnUnknownProduct() {
        // The comparator ranks by position in `productIDs`. Anything not in
        // that list sorts last rather than making the order arbitrary.
        let ranked = ["zzz.unknown", "dev.myhumblecoder.nutritioncoach.annual",
                      "dev.myhumblecoder.nutritioncoach.monthly"]
            .sorted { a, b in
                (Store.productIDs.firstIndex(of: a) ?? .max) < (Store.productIDs.firstIndex(of: b) ?? .max)
            }

        XCTAssertEqual(ranked, [
            "dev.myhumblecoder.nutritioncoach.monthly",
            "dev.myhumblecoder.nutritioncoach.annual",
            "zzz.unknown",
        ])
    }

    func testARejectedPostLeavesTheTransactionUnfinished() async {
        // Cannot drive a real Transaction without StoreKit, so this pins the
        // contract `handle` depends on: submit reports success, and the whole
        // retry story rests on that being false when the server refuses.
        let store = Store(submit: { _ in false })
        var reported: Bool?

        reported = await store.postForTesting("jws")

        XCTAssertEqual(reported, false)
        XCTAssertTrue(store.products.isEmpty)
    }

    func testRestoringWithNoEntitlementsPostsNothing() async {
        // No purchase, nothing to send. Posting an empty restore would have
        // the server verify a transaction that does not exist.
        var posted: [String] = []
        let store = Store(submit: { jws in
            await MainActor.run { posted.append(jws) }
            return true
        })

        await store.restore()

        XCTAssertTrue(posted.isEmpty)
    }
}
