import type { Metadata } from 'next'
import LegalPage, { Section } from '@/components/LegalPage'
import { SUPPORT_EMAIL } from '@/lib/contact'

export const metadata: Metadata = {
  title: 'Terms of Service — Roughly',
  description:
    'The agreement for using Roughly: what it is, what it is not, how the subscription works, and what happens to your data.',
}

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="9 September 2026">
      <p>
        These terms cover your use of Roughly, on the web and in the iPhone app. Using Roughly means
        you accept them. They are written to be read, not to be survived.
      </p>

      <Section heading="What Roughly is, and is not">
        <p>
          Roughly is a diet and training log with a conversational coach. It estimates calories and
          protein from what you tell it and from photos of your meals.
        </p>
        <p>
          <strong>It is not medical advice, and it is not a medical device.</strong> It does not
          diagnose, treat or prevent anything. It is not a substitute for a doctor, a dietitian or a
          therapist. If you have a medical condition, an eating disorder, or you are pregnant,
          talk to a professional rather than an app. If you are in crisis, contact your local
          emergency services.
        </p>
        <p>
          Every number Roughly produces is an estimate. The name is the honest part: a photograph
          cannot tell you how much oil was in the pan, and the figure on a package is a legal
          tolerance rather than a measurement. Treat the numbers as roughly right, because that is
          all they are.
        </p>
      </Section>

      <Section heading="The coach is generated by an AI model">
        <p>
          The coach&apos;s replies, and the calorie and protein estimates, are produced by{' '}
          <strong>Anthropic&apos;s Claude models</strong>. What you type, and the meal photos you
          send, are transmitted to Anthropic to produce those replies and estimates. Anthropic acts
          as a processor for Roughly and{' '}
          <strong>does not train its models on data sent through its API</strong>.
        </p>
        <p>
          Which specific Claude model is in use may change as models improve. What will not change
          without an update to these terms is the vendor, and the commitment above about training.
        </p>
        <p>
          Generated text is sometimes wrong, and occasionally confidently wrong. Every coach message
          in the app carries a Report control; please use it. Do not rely on the coach for anything
          that matters medically.
        </p>
        <p>
          Direct identifiers — email addresses, phone numbers, card numbers and similar — are
          stripped from your text before it is sent to the model. What you actually typed is kept in
          your own history. This is a safety net for things pasted by accident, not a guarantee:
          please do not put identifying details or anyone else&apos;s information into the coach.
        </p>
      </Section>

      <Section heading="Your account">
        <p>
          You need an account, and you must be at least 16 to have one. Keep your sign-in secure;
          you are responsible for what happens under your account.
        </p>
        <p>
          Do not use Roughly to break the law, to abuse the service, or to try to get around its
          usage limits. Those limits exist because every message and every photo costs real money to
          answer.
        </p>
      </Section>

      <Section heading="Subscriptions, trials and refunds">
        <ul className="list-disc space-y-1 pl-5">
          <li>
            Roughly is a paid subscription, sold through Apple as an in-app purchase. The price,
            billing period and any free trial are shown in the app before you buy, in your own
            currency.
          </li>
          <li>
            A subscription renews automatically at the end of each period unless you turn off
            auto-renew at least 24 hours before it ends. Renewal is charged to your Apple ID.
          </li>
          <li>
            If a free trial is offered, any unused part of it is forfeited when you buy a
            subscription.
          </li>
          <li>
            Manage or cancel your subscription in your Apple ID settings — Roughly cannot cancel it
            for you, and deleting the app does not cancel it.
          </li>
          <li>
            <strong>Refunds are handled by Apple, not by Roughly.</strong> Request one through
            Apple&apos;s support.
          </li>
          <li>
            When a subscription ends, your logged history stays visible and nothing is deleted. The
            parts that cost money to run — the coach, photo analysis and the weekly check-in —
            stop.
          </li>
        </ul>
      </Section>

      <Section heading="Your data">
        <p>
          What is collected, who processes it, and how to delete it is set out in the{' '}
          <a className="underline" href="/privacy">
            Privacy Policy
          </a>
          . Deleting your account deletes your data, including your meal photos.
        </p>
        <p>
          What you write and photograph stays yours. Roughly needs permission to store and process
          it only so far as running the service requires.
        </p>
      </Section>

      <Section heading="Availability, changes and endings">
        <p>
          Roughly is provided as it is, without warranty. It may be unavailable at times, and
          features may change. Where the law allows, liability is limited to what you paid in the
          twelve months before the problem.
        </p>
        <p>
          These terms may change. Material changes will be notified in the app or by email, and the
          date at the top of this page will move. Continuing to use Roughly after that means
          accepting the new terms.
        </p>
        <p>
          You can stop at any time by cancelling and deleting your account. Roughly may suspend an
          account that abuses the service or these terms.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions about these terms:{' '}
          <a className="underline" href={`mailto:${SUPPORT_EMAIL}`}>
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </Section>
    </LegalPage>
  )
}
